spring:
  application:
    name: fakeStackOverflow


thirdauthconfig:
  github:
    tokenUri: https://github.com/login/oauth/access_token
    userUri: https://api.github.com/user
    emailUri: https://api.github.com/email
    apiVersion: test
    clientId: test
    clientSecret: test


mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
  mapper-locations: classpath/com/what/spring/mapper/**.xml
  type-aliases-package: com.what.spring.pojo

frontend:
  root: http://localhost
  mainPage: test
